name: ğŸ” SBOM + Vuln

on:
  pull_request:
  push:
    branches: [ "main", "master" ]

jobs:
  sbom_and_vuln:
    uses: ./.github/workflows/syft-grype.yml
    with:
      target: "."
      artifact_name: "sbom-and-grype"
