name: ğŸ” Run SBOM - Syft

on:
  pull_request:
  push:
    branches: [ "main", "master" ]

jobs:
  sbom:
    uses: ./.github/workflows/syft.yml
    with:
      target: "."
      artifact_name: "sbom-syft"
      upload_artifacts: true
